config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken import views
from django.shortcuts import render


urlpatterns = [    

    
    path('admin/', admin.site.urls),
    path('', include('account_module.urls')),
    path('ads/', include('advertisement_module.urls')),
    path('job-company/', include('jobAndCompanyActivity_module.urls')),
    path('', include('home_module.urls')),
    path('panel/', include('userPanel_module.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', views.obtain_auth_token),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home_module/urls.py
from django.urls import path
from .views import HomeView, advertisement_detail, get_cities,SendReport,SendReportJobSeeker


urlpatterns = [
    path('',HomeView.as_view(),name="home"),
    path('detail/<code>',advertisement_detail,name='detail_advetisement_home'),
    path('report/<code>',SendReport.as_view(),name='report'),
    path('jobseeker/report/<code>',SendReportJobSeeker.as_view(),name='report_jobseeker'),

    path("get-cities", get_cities),
]

advertisement_module/models.py
import random
import jdatetime

from django.db import models
from django_jalali.db import models as jmodels
from iranian_cities.fields import CountyField, ProvinceField

from account_module.models import Employer, JobSeeker, User
from home_module.models import TehranDistrict
from jobAndCompanyActivity_module.models import Job


class Subscription(models.Model):
    name = models.CharField(
        max_length=120,
        verbose_name='نوع اشتراک'
    )
    price = models.IntegerField(
        default=0,
        verbose_name='قیمت',
        help_text='قیمت‌ها به تومان است - برای رایگان بودن، این بخش را نادیده بگیرید'
    )
    
    def __str__(self):
        return f"{self.name} {self.price:,} تومان"
    
    class Meta:
        verbose_name = 'تعرفه'
        verbose_name_plural = 'تعرفه‌ها'


class Skill(models.Model):
    name = models.CharField(
        max_length=220,
        verbose_name='مهارت‌های کارجو'
    )
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'مهارت'
        verbose_name_plural = 'مهارت‌ها'


class AdDisplayDuration(models.Model):
    days = models.IntegerField(
        verbose_name="روز",
        help_text='برای مثال 4'
    )
    price = models.IntegerField(
        verbose_name='قیمت',
        help_text='این قیمت کل است - مثلاً برای 7 روز، کل 7000 تومان'
    )
    
    def __str__(self):
        return f"{self.days} روز - {self.price:,} تومان"
    
    class Meta:
        verbose_name = 'زمان نمایش آگهی'
        verbose_name_plural = 'زمان نمایش آگهی‌ها'


class JobHistory(models.Model):
    place = models.CharField(
        max_length=220,
        verbose_name="نام مکان"
    )
    job = models.CharField(
        max_length=220,
        verbose_name="شغل شما"
    )
    duration = models.SmallIntegerField(
        verbose_name="مدت زمان",
        help_text="بر اساس ماه"
    )
    job_seeker = models.ForeignKey(
        JobSeeker,
        on_delete=models.CASCADE,
        verbose_name="کارجو",
        related_name="job_histories"
    )
    
    def __str__(self):
        return f"{self.job_seeker.user.last_name} - {self.job}"
    
    class Meta:
        verbose_name = 'سابقه کار'
        verbose_name_plural = 'سوابق'


class Advertisement(models.Model):
    # Choices مربوط به آگهی کارفرما
    GENDER = (('مرد', 'مرد'), ('زن', 'زن'))
    SOLDIER_STATUS = (
        ('پایان خدمت', 'پایان خدمت'),
        ('معافیت دائم', 'معافیت دائم'),
        ('معافیت تحصیلی', "معافیت تحصیلی")
    )
    DEGREE = (
        ("مهم نیست", "مهم نیست"),
        ('زیر دیپلم', 'زیر دیپلم'),
        ('دیپلم', 'دیپلم'),
        ('فوق دیپلم', 'فوق دیپلم'),
        ('لیسانس', 'لیسانس'),
        ('فوق لیسانس', 'فوق لیسانس'),
        ('دکترا', 'دکترا')
    )
    TYPEOFCOOPERATION = (
        ("مهم نیست", "مهم نیست"),
        ('کمتر از 3 سال', 'کمتر از 3 سال'),
        ("3 تا 6 سال", "3 تا 6 سال"),
        ("بیشتر از 6 سال", "بیشتر از 6 سال")
    )
    JOBTYPE = (
        ("تمام وقت", "تمام وقت"),
        ("پاره وقت", "پاره وقت"),
        ("دورکاری", "دورکاری"),
        ("کارآموزی", "کارآموزی")
    )
    STATUS = (
        ("unpaid", "در انتظار پرداخت"),
        ("pending", "در حال بررسی"),
        ("approved", "تایید شده"),
        ("rejected", "رد شده")
    )
    
    # فیلدهای جغرافیایی
    province = ProvinceField(
        verbose_name='نام استان'
    )
    county = CountyField(
        verbose_name="نام شهرستان"
    )
    district = models.ForeignKey(
        TehranDistrict,
        on_delete=models.CASCADE,
        verbose_name='نام منطقه',
        null=True,
        blank=True
    )
    
    # اطلاعات تعرفه و نمایش آگهی
    subscription = models.ForeignKey(
        Subscription,
        on_delete=models.PROTECT,
        related_name='advertisements',
        verbose_name='نوع اشتراک'
    )
    duration = models.ForeignKey(
        AdDisplayDuration,
        on_delete=models.CASCADE,
        related_name='advertisements',
        verbose_name='زمان نمایش'
    )
    
    created_at = jmodels.jDateTimeField(
        verbose_name='تاریخ ثبت',
        help_text='بعد از ثبت مقداردهی می‌شود',
        null=True,
        blank=True
    )
    expire_date = jmodels.jDateTimeField(
        verbose_name='تاریخ انقضا',
        null=True,
        blank=True,
        help_text='به‌صورت خودکار محاسبه می‌شود'
    )
    
    pay_status = models.BooleanField(
        verbose_name='وضعیت پرداخت',
        default=False
    )
    status = models.CharField(
        max_length=220,
        verbose_name="وضعیت",
        choices=STATUS,
        default="unpaid"
    )
    total_price = models.IntegerField(
        verbose_name='جمع کل',
        default=0,
        help_text='به صورت خودکار محاسبه می‌شود'
    )
    is_show = models.BooleanField(
        verbose_name='نمایش داده شود / نشود',
        default=False
    )
    
    # اطلاعات آگهی
    employer = models.ForeignKey(
        Employer,
        on_delete=models.CASCADE,
        verbose_name='کارفرما',
        related_name='advertisements'
    )
    advertise_code = models.CharField(
        max_length=220,
        unique=True,
        db_index=True,
        verbose_name='کدآگهی',
        help_text='بعد از ثبت مقداردهی می‌شود'
    )
    title = models.CharField(
        max_length=220,
        verbose_name="عنوان آگهی"
    )
    description_position = models.TextField(
        verbose_name='موقعیت شغلی'
    )
    gender = models.CharField(
        max_length=120,
        verbose_name='جنسیت',
        choices=GENDER
    )
    soldier_status = models.CharField(
        max_length=120,
        verbose_name='وضعیت سربازی',
        choices=SOLDIER_STATUS
    )
    degree = models.CharField(
        max_length=120,
        verbose_name='حداقل مدرک تحصیلی',
        choices=DEGREE
    )
    type_of_cooperation = models.CharField(
        max_length=220,
        verbose_name="سابقه کار مرتبط",
        choices=TYPEOFCOOPERATION
    )
    salary = models.CharField(
        max_length=220,
        verbose_name="حداقل دستمزد",
        help_text="درصورت خالی گذاشتن این بخش، مبلغ دستمزد توافقی می‌شود",
        null=True,
        blank=True
    )
    check_by_admin = models.BooleanField(
        verbose_name='مشاهده شده توسط ادمین',
        default=False
    )
    job_type = models.CharField(
        max_length=220,
        verbose_name='نوع شغل',
        choices=JOBTYPE
    )
    
    job = models.ForeignKey(
        Job,
        on_delete=models.CASCADE,
        verbose_name='شغل',
        related_name='advertisements'
    )
    skills = models.ManyToManyField(
        Skill,
        related_name='advertisements',
        verbose_name='مهارت‌های کارجو',
        blank=True
    )
    
    def __str__(self):
        return f"{self.advertise_code} - {self.employer.user}"
    
    class Meta:
        verbose_name = 'آگهی کارفرما'
        verbose_name_plural = 'آگهی کارفرمایان'
        ordering = ['-created_at']
    
    def save(self, *args, **kwargs):
        """
        در هنگام ذخیره اولیه‌ی آگهی:
          - در صورت خالی بودن فیلد دستمزد، مقدار 'توافقی' قرار می‌گیرد.
          - کد آگهی به‌صورت تصادفی تولید می‌شود.
          - تاریخ ثبت و تاریخ انقضا محاسبه می‌شوند.
          - جمع کل با استفاده از قیمت اشتراک و قیمت زمان نمایش تعیین می‌شود.
        """
        if not self.salary:
            self.salary = "توافقی"
        
        if not self.pk:
            self.advertise_code = str(random.randint(10000000, 99999999))
            self.total_price = self.subscription.price + self.duration.price
            self.created_at = jdatetime.datetime.now().replace(microsecond=0)
            self.expire_date = self.created_at + jdatetime.timedelta(days=self.duration.days)
        
        super().save(*args, **kwargs)


class AdvertisementJobSeeker(models.Model):
    # Choices مربوط به آگهی متقاضی کار
    GENDER = (('مرد', 'مرد'), ('زن', 'زن'))
    SOLDIER_STATUS = (
        ('پایان خدمت', 'پایان خدمت'),
        ('معافیت دائم', 'معافیت دائم'),
        ('معافیت تحصیلی', "معافیت تحصیلی")
    )
    DEGREE = (
        ('زیر دیپلم', 'زیر دیپلم'),
        ('دیپلم', 'دیپلم'),
        ('فوق دیپلم', 'فوق دیپلم'),
        ('لیسانس', 'لیسانس'),
        ('فوق لیسانس', 'فوق لیسانس'),
        ('دکترا', 'دکترا')
    )
    TYPEOFCOOPERATION = (
        ("سابقه ندارم", "سابقه ندارم"),
        ('کمتر از 3 سال', 'کمتر از 3 سال'),
        ("3 تا 6 سال", "3 تا 6 سال"),
        ("بیشتر از 6 سال", "بیشتر از 6 سال")
    )
    JOBTYPE = (
        ("تمام وقت", "تمام وقت"),
        ("پاره وقت", "پاره وقت"),
        ("دورکاری", "دورکاری"),
        ("کارآموزی", "کارآموزی")
    )
    STATUS = (
        ("unpaid", "در انتظار پرداخت"),
        ("pending", "در حال بررسی"),
        ("approved", "تایید شده"),
        ("rejected", "رد شده")
    )
    MARRIED_STATUS = (
        ("متاهل", "متاهل"),
        ("مجرد", "مجرد")
    )
    
    # فیلدهای جغرافیایی
    province = ProvinceField(verbose_name='نام استان')
    county = CountyField(verbose_name="نام شهرستان")
    district = models.ForeignKey(
        TehranDistrict,
        on_delete=models.CASCADE,
        verbose_name='نام منطقه',
        null=True,
        blank=True
    )
    
    # اطلاعات تعرفه و نمایش آگهی
    subscription = models.ForeignKey(
        Subscription,
        on_delete=models.PROTECT,
        related_name='advertisements_jobSeeker',
        verbose_name='نوع اشتراک'
    )
    duration = models.ForeignKey(
        AdDisplayDuration,
        on_delete=models.CASCADE,
        related_name='advertisements_jobSeeker',
        verbose_name='زمان نمایش'
    )
    
    created_at = jmodels.jDateTimeField(
        verbose_name='تاریخ ثبت',
        help_text='بعد از ثبت مقداردهی می‌شود',

home_module/models.py
from django.db import models
from iranian_cities.models import City
# Create your models here.

class TehranDistrict(models.Model):
    
    TEHRAN_DISTRICT = (
        ("1","منطقه 1"),
        ("2","منطقه 2"),
        ("3","منطقه 3"),
        ("4","منطقه 4"),
        ("5","منطقه 5"),
        ("6","منطقه 6"),
        ("7","منطقه 7"),
        ("8","منطقه 8"),
        ("9","منطقه 9"),
        ("10","منطقه 10"),
        ("11","منطقه 11"),
        ("12","منطقه 12"),
        ("13","منطقه 13"),
        ("14","منطقه 14"),
        ("15","منطقه 15"),
        ("16","منطقه 16"),
        ("17","منطقه 17"),
        ("18","منطقه 18"),
        ("19","منطقه 19"),
        ("20","منطقه 20"),
        ("21","منطقه 21"),
        ("22","منطقه 22"),
    )
    
    city = models.ForeignKey(City,on_delete=models.CASCADE,verbose_name="نام شهر",related_name="districts")
    name = models.CharField(max_length=220,verbose_name="نام منطقه",unique=True)
    
    class Meta:
        verbose_name = 'منطقه'
        verbose_name_plural = 'مناطق'
        
    def __str__(self):
        return self.name

home_module/forms.py
from django import forms  
from django.forms import widgets
from iranian_cities.models import Province,County

from advertisement_module.models import ReportAdvertisment
from .models import TehranDistrict

class LocationForm(forms.Form):
    
    JOBTYPE = (("select","انتخاب"),("تمام وقت","تمام وقت"),("پاره وقت","پاره وقت"),("دورکاری","دورکاری"),("کارآموزی","کارآموزی"))

    
    province = forms.ModelChoiceField(queryset=Province.objects.all(),required=False,label="استان",empty_label="انتخاب استان",widget=widgets.Select(attrs={'class':'form-select'}))
    county = forms.ModelChoiceField(queryset=County.objects.all(),required=False,label="شهر",empty_label="انتخاب شهر",widget=widgets.Select(attrs={'class':'form-select','onchange':'Check_county(value)'}))
    district=forms.ModelChoiceField(queryset=TehranDistrict.objects.all(),required=False,label="منطقه",empty_label="انتخاب منطقه",widget=widgets.Select(attrs={'class':'form-select','hidden':''}))
    job_type = forms.ChoiceField(choices=JOBTYPE,label="نوع شغل",required=False,widget=widgets.Select(attrs={'class':'form-select'}))
    search = forms.CharField(max_length=220,required=False,widget=widgets.TextInput(attrs={'placeholder':"عنوان شغلی",'type':'text','class':'form-control'}))
    

class ReportModelForm(forms.ModelForm):
        class Meta:
            model = ReportAdvertisment
            fields = ['message','image']

home_module/templates/home_module/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="fa">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
  جزئیات آگهی
    </title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-light" dir="rtl">
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="">آگهی</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
              aria-controls="navbarNav" aria-expanded="false" aria-label="">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'home' %}">خانه</a>
          </li>
          
          {% if  request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">خروج از حساب</a>
          </li>
          {% endif %}
            

        </ul>
      </div>
    </div>
  </nav>

<div class="container mt-5">
    <div class="card shadow p-4">
        <h3 class="text-center mb-4">جزئیات آگهی</h3>
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><strong>عنوان آگهی:</strong>{{data.title}}</li>
            <li class="list-group-item"><strong>شغل :</strong>{{data.job}}</li>
            <li class="list-group-item"><strong>توضیحات:</strong>{{data.description_position}}</li>
            <li class="list-group-item"><strong>جنسیت:</strong>{{data.get_gender_display}}</li>
            <li class="list-group-item"><strong>وضعیت سربازی:</strong>{{data.get_soldier_status_display}}</li>
            <li class="list-group-item"><strong>حداقل مدرک تحصیلی:</strong>{{data.degree}}</li>
            <li class="list-group-item"><strong>سابقه کار مرتبط:</strong>{{ data.type_of_cooperation }}</li>
            <li class="list-group-item"><strong>حداقل دستمزد:</strong>{{data.salary}}</li>
            <li class="list-group-item"><strong>استان:</strong>{{data.province}}</li>
            <li class="list-group-item"><strong>شهر:</strong>{{data.county}}</li>
            <li class="list-group-item"><strong>مهارت های مورد نیاز:</strong>
            
            {% for skill in data.skills.all %}
                {{skill}} - 
            {% endfor %}
                
            </li>

            
            <li class="list-group-item"><strong>میزان حقوق:</strong> ۱۰ میلیون تومان</li>
            <hr>
            
            
            {% if request.user.is_authenticated%}
            <li>اطلاعات شرکت :</li>
            <li>نام شرکت : {{employer.persian_compnay_name}}</li>
            <li>{{employer.description}}</li>
            <li>حوزه فعالیت : {{employer.company_filed}}</li>

            <hr>
            <li>اطلاعات تماس :</li>
            <li>شماره تلفن : {{employer.user.phone}}</li>
            {% else %}
            <p class="text-center alert alert-danger">برای مشاهده اطلاعات تماس <a href="{% url 'login' %}">وارد</a> شوید</p>
            {% endif %}
                
            
        </ul>

{% if request.user.is_authenticated %}
<a href="{% url 'report' data.advertise_code %}" class="btn btn-warning mt-3 d-block">گزارش</a>

{% endif %}
  
        <a href="{% url 'home' %}" class="btn btn-outline-secondary mt-3 d-block">بازگشت</a>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

  
</body>
</html>

home_module/templates/home_module/detail_jobseeker.html
{% load static %}
<!DOCTYPE html>
<html lang="fa">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
  جزئیات آگهی
    </title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-light" dir="rtl">
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="">آگهی</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
              aria-controls="navbarNav" aria-expanded="false" aria-label="">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'home' %}">خانه</a>
          </li>
          
          {% if  request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">خروج از حساب</a>
          </li>
          {% endif %}
            

        </ul>
      </div>
    </div>
  </nav>

<div class="container mt-5">
    <div class="card shadow p-4">
        <h3 class="text-center mb-4">جزئیات آگهی</h3>
        <ul class="list-group list-group-flush">
            {% if request.user.is_authenticated %}
            <li class="list-group-item"><strong>نام :</strong>{{data.jobSeeker.user.first_name}}</li>
            <li class="list-group-item"><strong>نام خانوادگی :</strong>{{data.jobSeeker.user.last_name}}</li>
            {% endif %}
            <li class="list-group-item"><strong>شغل مورد تقاضا :</strong>{{data.job_type}}</li>
            <li class="list-group-item"><strong>جنسیت:</strong>{{data.get_gender_display}}</li>
            <li class="list-group-item"><strong>وضعیت تاهل:</strong>{{data.married_status}}</li>
            <li class="list-group-item"><strong>تعداد فرزند:</strong>{{data.children_number}}</li>
            <li class="list-group-item"><strong>وضعیت سربازی:</strong>{{data.soldier_status}}</li>
            <li class="list-group-item"><strong>رشته تحصیلی :</strong>{{data.field_study}}</li>
            <li class="list-group-item"><strong>حداقل مدرک تحصیلی:</strong>{{data.get_degree_display}}</li>
            <li class="list-group-item"><strong>سابقه بیمه:</strong>{{data.get_insurance_display}}</li>
            <li class="list-group-item"><strong>دستمزد پیشنهادی:</strong>{{data.salary}}</li>
            <li class="list-group-item"><strong>سابقه آسیب شغلی :</strong>
            
            {% if data.history_injury %}
            {{data.history_injury}}
            {% else %}
            ندارد
            {% endif %}
                
            </li>

            {% if request.user.is_authenticated %}
            <li class="list-group-item"><strong>استان:</strong>{{province}}</li>
            <li class="list-group-item"><strong>شهر:</strong>{{county}}</li>
            {% if district %}
            <li class="list-group-item"><strong>منطقه:</strong>{{district}}</li>
            {% endif %}
            
            <li class="list-group-item"><strong>آدرس :</strong>{{data.address}}</li>
            <li class="list-group-item"><strong>تلفن :</strong>{{data.jobSeeker.user.phone}}</li>

            {% endif %}
            
            {% if data.description %}
            <li class="list-group-item"><strong>توضیحات تکمیلی:</strong>{{data.description}}</li>

            {% endif %}
            
            
                
                
            <li class="list-group-item"><strong>مهارت های مرتبط با حوزه فعالیت:</strong>
            
            {% for skill in data.skills.all %}
                {{skill}} - 
            {% endfor %}
                
            </li>

            
        </ul>
        {% if request.user.is_authenticated %}
<a href="{% url 'report_jobseeker' data.advertise_code %}" class="btn btn-warning mt-3 d-block">گزارش</a>

{% endif %}
        <a href="{% url 'home' %}" class="btn btn-outline-secondary mt-3 d-block">بازگشت</a>
    </div>
</div>
<hr>
<br>
{% if jobs %}
<p class="text-center">سوابق</p>


<div class="container">
    
<table class="table table-striped table-dark">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">مکان</th>
        <th scope="col">شغل</th>
        <th scope="col">مدت (براساس ماه)</th>

      </tr>
    </thead>
    <tbody>
      {% for job in jobs %}
        <tr>
            <th scope="row">{{forloop.counter}}</th>
        
        
        <td>{{job.place}}</td>
        <td>{{job.job}}</td>
        <td>{{job.duration}}</td>

          
            
        
    </tr>  
    {% endfor %}
      
    </tbody>
  </table>
</div>

  {% endif %}


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

  
</body>
</html>

home_module/templates/home_module/report.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>کزارش آگهی</title>
</head>
<body>

    <div>
        <p>گزارش آگهی  {{data.title}}</p>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form}}
            <button type="submit">ارسال گزارش</button>
        </form>
    </div>
    
</body>
</html>