advertisement_module/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

# ایمپورت ویوهای مورد نیاز
from .views import (
    AdvertisementModelViewSetApiView,
    CreateAdvertisement,
    CreateJobHistory,
    AdDisplayDurationModelViewSetApiView,
    JobSeekerCreateAdvertisement,
    JobSeekerUpdateAdvertisementView,
    SkillModelViewSetApiView,
    SubscriptionModelViewSetApiView,
    UpdateAdvertisementView,
    JobHistoryViewSetApiView,
    AdvertisementJobSeekerModelViewSetApiView,
    UpdateJobHistory,
    advertisement_detail,
    advertisement_list,
    dashboard,
    delete_advertisement,
    delete_job_history,
    delete_job_seeker_advertisement,
    get_cities,
    job_histories,
    job_seeker_advertisement_list,
    job_seeker_advertisement_detail
)

# تنظیم router برای API ها
router = DefaultRouter()
router.register("skill", SkillModelViewSetApiView)
router.register("duration", AdDisplayDurationModelViewSetApiView)
router.register("job-history", JobHistoryViewSetApiView)
router.register("subscription", SubscriptionModelViewSetApiView)
router.register("advertisement", AdvertisementModelViewSetApiView)
router.register("jobseeker/advertisement", AdvertisementJobSeekerModelViewSetApiView)

# تنظیم الگوهای URL
urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('manage', advertisement_list, name='advertisement_manage'),
    path('create', CreateAdvertisement.as_view(), name='create_advertisement'),
    path('update/<code>', UpdateAdvertisementView.as_view(), name='update_advertisement'),
    path('delete/<code>', delete_advertisement, name='delete_advertisement'),
    path('detail/<code>', advertisement_detail, name='detail_advertisement'),
    
    path("jobseeker/manage", job_seeker_advertisement_list, name='jobseeker_manage'),
    path('jobseeker/detail/<code>', job_seeker_advertisement_detail, name='jobseeker_detail_advertisement'),
    path('jobseeker/create', JobSeekerCreateAdvertisement.as_view(), name='jobseeker_create_advertisement'),
    path('jobseeker/update/<code>', JobSeekerUpdateAdvertisementView.as_view(), name='jobseeker_update_advertisement'),
    path('jobseeker/delete/<code>', delete_job_seeker_advertisement, name='jobseeker_delete_advertisement'),
    
    path("job_histories", job_histories, name='job_histories'),
    path('job-history/create', CreateJobHistory.as_view(), name='create_history'),
    path('job-history/update/<code>', UpdateJobHistory.as_view(), name='update_history'),
    path('job-history/delete/<code>', delete_job_history, name='delete_history'),
    
    path("get-cities", get_cities, name="get_cities"),
    path("api/", include(router.urls))
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken import views
from django.shortcuts import render


urlpatterns = [    

    
    path('admin/', admin.site.urls),
    path('', include('account_module.urls')),
    path('ads/', include('advertisement_module.urls')),
    path('job-company/', include('jobAndCompanyActivity_module.urls')),
    path('', include('home_module.urls')),
    path('panel/', include('userPanel_module.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api-token-auth/', views.obtain_auth_token),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

advertisement_module/models.py
import random
import jdatetime

from django.db import models
from django_jalali.db import models as jmodels
from iranian_cities.fields import CountyField, ProvinceField

from account_module.models import Employer, JobSeeker, User
from home_module.models import TehranDistrict
from jobAndCompanyActivity_module.models import Job


class Subscription(models.Model):
    name = models.CharField(
        max_length=120,
        verbose_name='نوع اشتراک'
    )
    price = models.IntegerField(
        default=0,
        verbose_name='قیمت',
        help_text='قیمت‌ها به تومان است - برای رایگان بودن، این بخش را نادیده بگیرید'
    )
    
    def __str__(self):
        return f"{self.name} {self.price:,} تومان"
    
    class Meta:
        verbose_name = 'تعرفه'
        verbose_name_plural = 'تعرفه‌ها'


class Skill(models.Model):
    name = models.CharField(
        max_length=220,
        verbose_name='مهارت‌های کارجو'
    )
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = 'مهارت'
        verbose_name_plural = 'مهارت‌ها'


class AdDisplayDuration(models.Model):
    days = models.IntegerField(
        verbose_name="روز",
        help_text='برای مثال 4'
    )
    price = models.IntegerField(
        verbose_name='قیمت',
        help_text='این قیمت کل است - مثلاً برای 7 روز، کل 7000 تومان'
    )
    
    def __str__(self):
        return f"{self.days} روز - {self.price:,} تومان"
    
    class Meta:
        verbose_name = 'زمان نمایش آگهی'
        verbose_name_plural = 'زمان نمایش آگهی‌ها'


class JobHistory(models.Model):
    place = models.CharField(
        max_length=220,
        verbose_name="نام مکان"
    )
    job = models.CharField(
        max_length=220,
        verbose_name="شغل شما"
    )
    duration = models.SmallIntegerField(
        verbose_name="مدت زمان",
        help_text="بر اساس ماه"
    )
    job_seeker = models.ForeignKey(
        JobSeeker,
        on_delete=models.CASCADE,
        verbose_name="کارجو",
        related_name="job_histories"
    )
    
    def __str__(self):
        return f"{self.job_seeker.user.last_name} - {self.job}"
    
    class Meta:
        verbose_name = 'سابقه کار'
        verbose_name_plural = 'سوابق'


class Advertisement(models.Model):
    # Choices مربوط به آگهی کارفرما
    GENDER = (('مرد', 'مرد'), ('زن', 'زن'))
    SOLDIER_STATUS = (
        ('پایان خدمت', 'پایان خدمت'),
        ('معافیت دائم', 'معافیت دائم'),
        ('معافیت تحصیلی', "معافیت تحصیلی")
    )
    DEGREE = (
        ("مهم نیست", "مهم نیست"),
        ('زیر دیپلم', 'زیر دیپلم'),
        ('دیپلم', 'دیپلم'),
        ('فوق دیپلم', 'فوق دیپلم'),
        ('لیسانس', 'لیسانس'),
        ('فوق لیسانس', 'فوق لیسانس'),
        ('دکترا', 'دکترا')
    )
    TYPEOFCOOPERATION = (
        ("مهم نیست", "مهم نیست"),
        ('کمتر از 3 سال', 'کمتر از 3 سال'),
        ("3 تا 6 سال", "3 تا 6 سال"),
        ("بیشتر از 6 سال", "بیشتر از 6 سال")
    )
    JOBTYPE = (
        ("تمام وقت", "تمام وقت"),
        ("پاره وقت", "پاره وقت"),
        ("دورکاری", "دورکاری"),
        ("کارآموزی", "کارآموزی")
    )
    STATUS = (
        ("unpaid", "در انتظار پرداخت"),
        ("pending", "در حال بررسی"),
        ("approved", "تایید شده"),
        ("rejected", "رد شده")
    )
    
    # فیلدهای جغرافیایی
    province = ProvinceField(
        verbose_name='نام استان'
    )
    county = CountyField(
        verbose_name="نام شهرستان"
    )
    district = models.ForeignKey(
        TehranDistrict,
        on_delete=models.CASCADE,
        verbose_name='نام منطقه',
        null=True,
        blank=True
    )
    
    # اطلاعات تعرفه و نمایش آگهی
    subscription = models.ForeignKey(
        Subscription,
        on_delete=models.PROTECT,
        related_name='advertisements',
        verbose_name='نوع اشتراک'
    )
    duration = models.ForeignKey(
        AdDisplayDuration,
        on_delete=models.CASCADE,
        related_name='advertisements',
        verbose_name='زمان نمایش'
    )
    
    created_at = jmodels.jDateTimeField(
        verbose_name='تاریخ ثبت',
        help_text='بعد از ثبت مقداردهی می‌شود',
        null=True,
        blank=True
    )
    expire_date = jmodels.jDateTimeField(
        verbose_name='تاریخ انقضا',
        null=True,
        blank=True,
        help_text='به‌صورت خودکار محاسبه می‌شود'
    )
    
    pay_status = models.BooleanField(
        verbose_name='وضعیت پرداخت',
        default=False
    )
    status = models.CharField(
        max_length=220,
        verbose_name="وضعیت",
        choices=STATUS,
        default="unpaid"
    )
    total_price = models.IntegerField(
        verbose_name='جمع کل',
        default=0,
        help_text='به صورت خودکار محاسبه می‌شود'
    )
    is_show = models.BooleanField(
        verbose_name='نمایش داده شود / نشود',
        default=False
    )
    
    # اطلاعات آگهی
    employer = models.ForeignKey(
        Employer,
        on_delete=models.CASCADE,
        verbose_name='کارفرما',
        related_name='advertisements'
    )
    advertise_code = models.CharField(
        max_length=220,
        unique=True,
        db_index=True,
        verbose_name='کدآگهی',
        help_text='بعد از ثبت مقداردهی می‌شود'
    )
    title = models.CharField(
        max_length=220,
        verbose_name="عنوان آگهی"
    )
    description_position = models.TextField(
        verbose_name='موقعیت شغلی'
    )
    gender = models.CharField(
        max_length=120,
        verbose_name='جنسیت',
        choices=GENDER
    )
    soldier_status = models.CharField(
        max_length=120,
        verbose_name='وضعیت سربازی',
        choices=SOLDIER_STATUS
    )
    degree = models.CharField(
        max_length=120,
        verbose_name='حداقل مدرک تحصیلی',
        choices=DEGREE
    )
    type_of_cooperation = models.CharField(
        max_length=220,
        verbose_name="سابقه کار مرتبط",
        choices=TYPEOFCOOPERATION
    )
    salary = models.CharField(
        max_length=220,
        verbose_name="حداقل دستمزد",
        help_text="درصورت خالی گذاشتن این بخش، مبلغ دستمزد توافقی می‌شود",
        null=True,
        blank=True
    )
    check_by_admin = models.BooleanField(
        verbose_name='مشاهده شده توسط ادمین',
        default=False
    )
    job_type = models.CharField(
        max_length=220,
        verbose_name='نوع شغل',
        choices=JOBTYPE
    )
    
    job = models.ForeignKey(
        Job,
        on_delete=models.CASCADE,
        verbose_name='شغل',
        related_name='advertisements'
    )
    skills = models.ManyToManyField(
        Skill,
        related_name='advertisements',
        verbose_name='مهارت‌های کارجو',
        blank=True
    )
    
    def __str__(self):
        return f"{self.advertise_code} - {self.employer.user}"
    
    class Meta:
        verbose_name = 'آگهی کارفرما'
        verbose_name_plural = 'آگهی کارفرمایان'
        ordering = ['-created_at']
    
    def save(self, *args, **kwargs):
        """
        در هنگام ذخیره اولیه‌ی آگهی:
          - در صورت خالی بودن فیلد دستمزد، مقدار 'توافقی' قرار می‌گیرد.
          - کد آگهی به‌صورت تصادفی تولید می‌شود.
          - تاریخ ثبت و تاریخ انقضا محاسبه می‌شوند.
          - جمع کل با استفاده از قیمت اشتراک و قیمت زمان نمایش تعیین می‌شود.
        """
        if not self.salary:
            self.salary = "توافقی"
        
        if not self.pk:
            self.advertise_code = str(random.randint(10000000, 99999999))
            self.total_price = self.subscription.price + self.duration.price
            self.created_at = jdatetime.datetime.now().replace(microsecond=0)
            self.expire_date = self.created_at + jdatetime.timedelta(days=self.duration.days)
        
        super().save(*args, **kwargs)


class AdvertisementJobSeeker(models.Model):
    # Choices مربوط به آگهی متقاضی کار
    GENDER = (('مرد', 'مرد'), ('زن', 'زن'))
    SOLDIER_STATUS = (
        ('پایان خدمت', 'پایان خدمت'),
        ('معافیت دائم', 'معافیت دائم'),
        ('معافیت تحصیلی', "معافیت تحصیلی")
    )
    DEGREE = (
        ('زیر دیپلم', 'زیر دیپلم'),
        ('دیپلم', 'دیپلم'),
        ('فوق دیپلم', 'فوق دیپلم'),
        ('لیسانس', 'لیسانس'),
        ('فوق لیسانس', 'فوق لیسانس'),
        ('دکترا', 'دکترا')
    )
    TYPEOFCOOPERATION = (
        ("سابقه ندارم", "سابقه ندارم"),
        ('کمتر از 3 سال', 'کمتر از 3 سال'),
        ("3 تا 6 سال", "3 تا 6 سال"),
        ("بیشتر از 6 سال", "بیشتر از 6 سال")
    )
    JOBTYPE = (
        ("تمام وقت", "تمام وقت"),
        ("پاره وقت", "پاره وقت"),
        ("دورکاری", "دورکاری"),
        ("کارآموزی", "کارآموزی")
    )
    STATUS = (
        ("unpaid", "در انتظار پرداخت"),
        ("pending", "در حال بررسی"),
        ("approved", "تایید شده"),
        ("rejected", "رد شده")
    )
    MARRIED_STATUS = (
        ("متاهل", "متاهل"),
        ("مجرد", "مجرد")
    )
    
    # فیلدهای جغرافیایی
    province = ProvinceField(verbose_name='نام استان')
    county = CountyField(verbose_name="نام شهرستان")
    district = models.ForeignKey(
        TehranDistrict,
        on_delete=models.CASCADE,
        verbose_name='نام منطقه',
        null=True,
        blank=True
    )
    
    # اطلاعات تعرفه و نمایش آگهی
    subscription = models.ForeignKey(
        Subscription,
        on_delete=models.PROTECT,
        related_name='advertisements_jobSeeker',
        verbose_name='نوع اشتراک'
    )
    duration = models.ForeignKey(
        AdDisplayDuration,
        on_delete=models.CASCADE,
        related_name='advertisements_jobSeeker',
        verbose_name='زمان نمایش'
    )
    
    created_at = jmodels.jDateTimeField(
        verbose_name='تاریخ ثبت',
        help_text='بعد از ثبت مقداردهی می‌شود',

advertisement_module/forms.py
from django import forms
from .models import Advertisement, ReportAdvertisment, JobHistory, AdvertisementJobSeeker


class AdvertisementModelForm(forms.ModelForm):
    class Meta:
        model = Advertisement
        exclude = [
            'employer',
            'advertise_code',
            'created_at',
            'expire_date',
            'pay_status',
            'check_by_admin',
            'status',
            'is_show',
            'total_price',
            'province',
            'county',
            'district'
        ]


class UpdateAdvertisementModelForm(forms.ModelForm):
    class Meta:
        model = Advertisement
        exclude = [
            'employer',
            'advertise_code',
            'created_at',
            'expire_date',
            'pay_status',
            'check_by_admin',
            'status',
            'is_show',
            'total_price',
            'province',
            'county',
            'district'
        ]


class JobHistoryModelForm(forms.ModelForm):
    class Meta:
        model = JobHistory
        exclude = ['job_seeker']


class JobSeekerAdvertisementModelForm(forms.ModelForm):
    class Meta:
        model = AdvertisementJobSeeker
        exclude = [
            'jobSeeker',
            'advertise_code',
            'created_at',
            'expire_date',
            'pay_status',
            'check_by_admin',
            'status',
            'is_show',
            'total_price',
            'province',
            'county',
            'district'
        ]
        widgets = {
            'gender': forms.widgets.Select(attrs={'onchange': "check_gender(this)"})
        }

advertisement_module/templates/advertisement_module/detail.html
{% extends 'advertisement_module/_layout.html' %}


{% block page_title %}
  {{data.title}}
{% endblock  %}
  


{% block container %}
<div class="container mt-5">
    <div class="card shadow p-4">
        <h3 class="text-center mb-4">جزئیات آگهی</h3>
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><strong>عنوان آگهی:</strong>{{data.title}}</li>
            <li class="list-group-item"><strong>شغل :</strong>{{data.job}}</li>
            <li class="list-group-item"><strong>توضیحات:</strong>{{data.description_position}}</li>
            <li class="list-group-item"><strong>جنسیت:</strong>{{data.get_gender_display}}</li>
            <li class="list-group-item"><strong>وضعیت سربازی:</strong>{{data.soldier_status}}</li>
            <li class="list-group-item"><strong>حداقل مدرک تحصیلی:</strong>{{data.get_degree_display}}</li>
            <li class="list-group-item"><strong>سابقه کار مرتبط:</strong>{{data.get_type_of_cooperation_display}}</li>
            <li class="list-group-item"><strong>حداقل دستمزد:</strong>{{data.salary}}</li>
            <li class="list-group-item"><strong>استان:</strong>{{province}}</li>
            <li class="list-group-item"><strong>شهر:</strong>{{county}}</li>
            
            {% if district %}
            <li class="list-group-item"><strong>منطقه:</strong>{{district}}</li>
            {% endif %}
                

            <li class="list-group-item"><strong>نوع اشتراک :</strong>{{data.subscription}}</li>
            <li class="list-group-item"><strong>زمان نمایش آگهی:</strong>{{data.duration}}</li>
            <li class="list-group-item"><strong>تاریخ انقضا آگهی:</strong>{{data.expire_date}}</li>
            <li class="list-group-item"><strong>مهارت های مورد نیاز:</strong>
            
            {% for skill in data.skills.all %}
                {{skill}} - 
            {% endfor %}
                
            </li>

            
            <li class="list-group-item"><strong>میزان حقوق:</strong> ۱۰ میلیون تومان</li>
            <li class="list-group-item"><strong>وضعیت:</strong> <span class="">{{data.get_status_display}}</span></li>
        </ul>
        <a href="{% url 'dashboard' %}" class="btn btn-outline-secondary mt-3 d-block">بازگشت</a>
    </div>
</div>

{% endblock %}

advertisement_module/templates/advertisement_module/detail_jobseeker.html
{% extends 'advertisement_module/_jobseeker_layout.html' %}


{% block page_title %}
  {{data.title}}
{% endblock  %}
  


{% block container %}
<div class="container mt-5">
    <div class="card shadow p-4">
        <h3 class="text-center mb-4">جزئیات آگهی</h3>
        <ul class="list-group list-group-flush">

            <li class="list-group-item"><strong>شغل مورد تقاضا :</strong>{{data.job_type}}</li>
            <li class="list-group-item"><strong>جنسیت:</strong>{{data.get_gender_display}}</li>
            <li class="list-group-item"><strong>وضعیت تاهل:</strong>{{data.married_status}}</li>
            <li class="list-group-item"><strong>تعداد فرزند:</strong>{{data.children_number}}</li>
            <li class="list-group-item"><strong>وضعیت سربازی:</strong>{{data.soldier_status}}</li>
            <li class="list-group-item"><strong>رشته تحصیلی :</strong>{{data.field_study}}</li>
            <li class="list-group-item"><strong>حداقل مدرک تحصیلی:</strong>{{data.get_degree_display}}</li>
            <li class="list-group-item"><strong>سابقه بیمه:</strong>{{data.get_insurance_display}}</li>
            <li class="list-group-item"><strong>دستمزد پیشنهادی:</strong>{{data.salary}}</li>
            <li class="list-group-item"><strong>سابقه آسیب شغلی :</strong>{{data.history_injury}}</li>
            <li class="list-group-item"><strong>استان:</strong>{{province}}</li>
            <li class="list-group-item"><strong>شهر:</strong>{{county}}</li>
            {% if district %}
            <li class="list-group-item"><strong>منطقه:</strong>{{district}}</li>
            {% endif %}
            
            {% if data.description %}
            <li class="list-group-item"><strong>توضیحات تکمیلی:</strong>{{data.description}}</li>

            {% endif %}
            <li class="list-group-item"><strong>آدرس :</strong>{{data.address}}</li>
                
            
            
                

            <li class="list-group-item"><strong>نوع اشتراک :</strong>{{data.subscription}}</li>
            <li class="list-group-item"><strong>زمان نمایش آگهی:</strong>{{data.duration}}</li>
            <li class="list-group-item"><strong>تاریخ انقضا آگهی:</strong>{{data.expire_date}}</li>
            <li class="list-group-item"><strong>مهارت های مرتبط با حوزه فعالیت:</strong>
            
            {% for skill in data.skills.all %}
                {{skill}} - 
            {% endfor %}
                
            </li>

            
            <li class="list-group-item"><strong>وضعیت:</strong> <span class="">{{data.get_status_display}}</span></li>
        </ul>
        <a href="{% url 'jobseeker_manage' %}" class="btn btn-outline-secondary mt-3 d-block">بازگشت</a>
    </div>
</div>



{% endblock %}

advertisement_module/templates/advertisement_module/manage.html

{% extends 'advertisement_module/_layout.html' %}


{% block page_title %}
  خانه
{% endblock  %}
  


{% block container %}






<div class="container mt-5">
    <div class="card shadow p-4">
        <h3 class="text-center mb-4">مدیریت آگهی‌ها</h3>
        <table class="table table-bordered table-hover">
            <thead class="table-dark">
                <tr>
                    <th>عنوان</th>
                    <th>وضعیت</th>
                    <th class="text-center">عملیات</th>
                </tr>
            </thead>
            <tbody>
                
                
                {% if advertisements %}
                    
                
                    

                {% for data in advertisements %}
                  
                  {% if data.pay_status == 1 and data.status == "approved" %}
                          
                <tr>
                    <td>{{data.title}}</td>
                    <td><span class="badge bg-success">{{data.get_status_display}}</span></td>
                    <td class="text-center">
                        <a href="{% url 'detail_advetisement' data.advertise_code %}" class="btn btn-info btn-sm">جزئیات</a>
                        <a href="{% url 'update_advetisement' data.advertise_code %}" class="btn btn-warning btn-sm">ویرایش</a>
                        <a href="{% url 'delete_advetisement' data.advertise_code %}" class="btn btn-danger btn-sm">حذف</a>
                    </td>
                </tr>
                {% endif %}
                {% endfor %}
                {% endif %}
            </tbody>
        </table>
        <h4 class="mt-4">آگهی‌های پیش‌نویس</h4>
        <table class="table table-warning table-hover">
            <thead>
                <tr>
                    <th>عنوان</th>
                    <th>وضعیت</th>
                    <th class="text-center">عملیات</th>
                </tr>
            </thead>
            <tbody>
                
                {% for data in advertisements %}
                    
                    {% if data.status != "approved" %}                  
                        
                <tr>
                    <td>{{data.title}}</td>
                    <td><span class="badge bg-secondary">پیش‌نویس ({{ data.get_status_display }})</span></td>
                    <td class="text-center">
                        
                        {% if data.status == "unpaid" %}
                        <button class="btn btn-success btn-sm">پرداخت و انتشار</button>

                        {% endif %}
                        <a href="{% url 'detail_advetisement' data.advertise_code %}" class="btn btn-info btn-sm">جزئیات</a>
                        <a href="{% url 'update_advetisement' data.advertise_code %}" class="btn btn-warning btn-sm">ویرایش</a>
                        <a href="{% url 'delete_advetisement' data.advertise_code %}" class="btn btn-danger btn-sm">حذف</a>
                    </td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
        <a href="{% url 'dashboard' %}" class="btn btn-outline-secondary mt-3 d-block">بازگشت</a>
    </div>
</div>


{% endblock %}

advertisement_module/templates/advertisement_module/manage_jobSeeker.html
{% extends 'advertisement_module/_jobseeker_layout.html' %}


{% block page_title %}
خانه
{% endblock %}


advertise

{% block container %}



<div class="container mt-5">
    <div class="card shadow p-4">
        <h3 class="text-center mb-4">مدیریت آگهی‌ها</h3>
        {% if data %}
        <table class="table table-bordered table-hover">
            <thead class="table-dark">
                <tr>
                    <th>عنوان</th>
                    <th>وضعیت</th>
                    <th class="text-center">عملیات</th>
                </tr>
            </thead>
            
            <tbody>
                {% if data.pay_status == 1 and data.status == "approved" %}

                <tr>
                    <td>آگهی متقاضی کار</td>
                    <td><span class="badge bg-success">{{data.get_status_display}}</span></td>
                    <td class="text-center">
                        <a href="{% url 'jobseeker_detail_advetisement' data.advertise_code %}"
                            class="btn btn-info btn-sm">جزئیات</a>
                        <a href="{% url 'jobseeker_update_advetisement' data.advertise_code %}"
                            class="btn btn-warning btn-sm">ویرایش</a>
                        <a href="{% url 'jobseeker_delete_advetisement' data.advertise_code %}"
                            class="btn btn-danger btn-sm">حذف</a>
                    </td>
                </tr>
                {% endif %}

            </tbody>
        </table>
        <h4 class="mt-4">آگهی‌های پیش‌نویس</h4>
        <table class="table table-warning table-hover">
            <thead>
                <tr>
                    <th>عنوان</th>
                    <th>وضعیت</th>
                    <th class="text-center">عملیات</th>
                </tr>
            </thead>
            <tbody>



                {% if data.status != "approved" %}

                <tr>
                    <td>آگهی متقاضی کار</td>
                    <td><span class="badge bg-secondary">پیش‌نویس ({{ data.get_status_display }})</span></td>
                    <td class="text-center">

                        {% if data.status == "unpaid" %}
                        <button class="btn btn-success btn-sm">پرداخت و انتشار</button>

                        {% endif %}
                        <a href="{% url 'jobseeker_detail_advetisement' data.advertise_code %}"
                            class="btn btn-info btn-sm">جزئیات</a>
                        <a href="{% url 'jobseeker_update_advetisement' data.advertise_code %}"
                            class="btn btn-warning btn-sm">ویرایش</a>
                        <a href="{% url 'jobseeker_delete_advetisement' data.advertise_code %}"
                            class="btn btn-danger btn-sm">حذف</a>
                    </td>
                </tr>
                {% endif %}
            </tbody>
        </table>
        {% else %}
        <p class="text-center">آگهی وجود ندارد <a href="{% url 'jobseeker_create_advertisement' %}">ایجاد </a> کنید</p>
        {% endif %}

        <hr>
        <br>
        <p class="text-center">سوابق</p>
        <p class="text-warning text-center">شما نمیتوانید بیشتر از 5 سابقه کار برای خود ثبت کنید</p>

        {% if jobs %}
        <div class="container">

            <table class="table table-striped table-dark">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">مکان</th>
                        <th scope="col">شغل</th>
                        <th scope="col">مدت (براساس ماه)</th>
                        <th scope="col">عملیات</th>
                    </tr>
                </thead>
                <tbody>
                    {% for job in jobs %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>


                        <td>{{job.place}}</td>
                        <td>{{job.job}}</td>
                        <td>{{job.duration}}</td>
                        <td>
                            <a class="btn btn-warning" href="{% url 'update_history' job.pk %}">ویرایش</a>
                            <a class="btn btn-danger" href="{% url 'delete_history' job.pk %}">حذف</a>
                            <a class="btn btn-info" href="{% url 'jobseeker_manage' %}">بازگشت</a>
                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
        {% else %}
        <p class="text-center text text-danger">
            سابقه ای وجود ندارد درصورت تمایل <a href="{% url 'create_history' %}">ایجاد</a> کنید.
        </p>

        {% endif %}

        <a href="{% url 'jobseeker_manage' %}" class="btn btn-outline-secondary mt-3 d-block">بازگشت</a>
    </div>
</div>
{% endblock %}